import tkinter as tk
from tkinter import ttk
# have to add DOB,gender and address
root = tk.Tk()
# root = tk.Toplevel(root, )

frame = tk.LabelFrame(root, text='New Patient Registration', padx=10, pady=10, bg="lightblue")
frame.grid(row=0, column=0, sticky='news')

fnameLabel = tk.Label(frame, text='First Name: ')
fnameBox = ttk.Entry(frame, width=30)
lnameLabel = tk.Label(frame, text='Last Name: ')
lnameBox = ttk.Entry(frame, width=30)
unameLabel = tk.Label(frame, text='Username: ')
unameBox = tk.Entry(frame, width=30)
passLabel = tk.Label(frame, text='Password: ')
passBox = ttk.Entry(frame, width=30)
phoneLabel = tk.Label(frame, text='Phone Number: ')
phoneBox = ttk.Entry(frame, width=30)
emailLabel = tk.Label(frame, text='E-mail: ')
emailBox = ttk.Entry(frame, width=30)
submit = tk.Button(frame, text='Submit')

fnameLabel.grid(row=0, column=0)
fnameBox.grid(row=0, column=1)
lnameLabel.grid(row=1, column=0)
lnameBox.grid(row=1, column=1)
unameLabel.grid(row=2, column=0)
unameBox.grid(row=2, column=1)
passLabel.grid(row=3, column=0)
passBox.grid(row=3, column=1)
phoneLabel.grid(row=4, column=0)
phoneBox.grid(row=4, column=1)
emailLabel.grid(row=5, column=0)
emailBox.grid(row=5, column=1)
submit.grid(row=6, column=0, columnspan=2)

root.rowconfigure (0, weight=1, minsize=500)
root.columnconfigure (0, weight=1, minsize=700)
frame.rowconfigure (0, weight=1)
frame.rowconfigure (1, weight=1)
frame.rowconfigure (2, weight=1)
frame.rowconfigure (3, weight=1)
frame.rowconfigure (4, weight=1)
frame.rowconfigure (5, weight=1)
frame.rowconfigure (6, weight=2)
frame.columnconfigure (0, weight=1)
frame.columnconfigure (1, weight=1)

root.mainloop()